{
 "title": "Cache",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "memory alloc MB/s",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %/s",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC srv msg sent /s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(grpc_server_msg_sent_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC srv msg rcv/s",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(grpc_server_msg_received_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  }
 ]
}