name: CI/CD Test per PR.
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "!releases/**"

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go test -cover ./...
        env:
          CGO_ENABLED: 0
